package com.banglalink.toffee.util

object ConvivaConstants {
    const val APP_VERSION = "c3.app.version"
    const val CONTENT_TYPE = "c3.cm.contentType"
    const val CHANNEL = "c3.cm.channel"
    const val BRAND = "c3.cm.brand"
    const val AFFILIATE = "c3.cm.affiliate"
    const val CATEGORY_TYPE = "c3.cm.categoryType"
    const val NAME = "c3.cm.name"
    const val ID = "c3.cm.id"
    const val SERIES_NAME = "c3.cm.seriesName"
    const val SEASON_NUMBER = "c3.cm.seasonNumber"
    const val SHOW_TITLE = "c3.cm.showTitle"
    const val EPISODE_NUMBER = "c3.cm.episodeNumber"
    const val GENRE = "c3.cm.genre"
    const val GENRE_LIST = "c3.cm.genreList"
    const val UTM_TRACKING_URL = "c3.cm.utmTrackingUrl"
    const val AD_TECHNOLOGY = "c3.ad.technology"
    const val AD_ID = "c3.ad.id"
    const val AD_SYSTEM = "c3.ad.system"
    const val AD_POSITION = "c3.ad.position"
    const val AD_IS_SLATE = "c3.ad.isSlate"
    const val AD_MEDIA_FILE_API_FRAMEWORK = "c3.ad.mediaFileApiFramework"
    const val AD_STITCHER = "c3.ad.adStitcher"
    const val AD_FIRST_AD_SYSTEM = "c3.ad.firstAdSystem"
    const val AD_FIRST_AD_ID = "c3.ad.firstAdId"
    const val AD_FIRST_CREATIVE_ID = "c3.ad.firstCreativeId"
    const val AD_CREATIVE_ID = "c3.ad.creativeId"
}